### ISSUE TITLE
Refactor internal_interpreter, execute method

### ISSUE THREAD

**Issue by ftomassetti** [smeup/jariko#10]
The complexity of this method is exploding, therefore we would like to decompose it.

1. We would like to extract the most complex cases (e.g., `ForStmt`, `DoStmt`) to single functions, passing an interface representing the core functionality of the interpreter (InterpreterCore)
2. Reorder the entries based on the frequency of the statements in the smeup's codebase
3. Possibly, replace the when statement with an hashmap. The name of the classes will be the keys, while the values will be lambdas or objects containing the logic to execute the corresponding statements

InterpreterCore should contain at least interpret, execute, assign, get, log

**Comment by ftomassetti** [comment]
For this one we are waiting for performance tests. Correct, @lanarimarco ?

**Comment by lanarimarco** [comment]
Yes
