### ISSUE TITLE
Unable to instantiate variable via MOVEL(P)

### ISSUE THREAD

**Issue by parodi-smeup** [smeup/jariko#116]
MOVEL(P) doesn't work properly cause variable can't be declared and instantiated:
ie: 
C                   MOVEL(P)  'XXXXX'       VAR               5

**Comment by benetti-smeup** [comment]
Frank, the issue is only with MOVEL(P) , with extender P , or also with MOVEL without extender?

**Comment by f-lombardo** [comment]
The issue holds both for MOVEL(P) and for MOVE. I added one test for this:
https://github.com/smeup/jariko/commit/d50214cde4cd2161286d9fecfdae908eca30c29f
