### ISSUE TITLE
Running tests from right click on Intellij

### ISSUE THREAD

**Issue by f-lombardo** [smeup/jariko#25]
It should be possible to run the tests using "right click" on the test folder from IntelliJ. So we have to craft tests in order to be less sensitive to the current directory.

**Comment by f-lombardo** [comment]
Uhm, I think it doesn't work yet

**Comment by lanarimarco** [comment]
May be you are speaking about Jardis.   
If you are courious you can see this video [JRPGLE in the wonderland](https://youtu.be/RQcZXFQ-hQU)
