### ISSUE TITLE
Create a list of presentations

### ISSUE THREAD

**Issue by ftomassetti** [smeup/jariko#74]
Adding:
* https://vimeo.com/showcase/6668137/video/381624384
* https://www.youtube.com/watch?v=ykmgp7iN-_k&t=1s

Plus the slides

**Comment by f-lombardo** [comment]
Great idea!
Here are the slides from my IAD's presentation:
https://www.slideshare.net/francolombardo/tdd-su-as400-con-kotlin-si-pu-fare-italian-agile-days-2019

I will create an English version soon

**Comment by f-lombardo** [comment]
Here is the English version:
https://www.slideshare.net/francolombardo/unit-testing-on-as400-yes-we-can-with-kotlin

**Comment by ftomassetti** [comment]
Federico should add his own slides

**Comment by ftomassetti** [comment]
Done
