### ISSUE TITLE
Investigate error in MUTE09_05

### ISSUE THREAD

**Issue by ftomassetti** [smeup/jariko#92]
Program MUTE09_05 fails, when considering the comparison of arrays and strings with different dimensions.

This has been reported by @benetti-smeup

**Comment by ftomassetti** [comment]
The reason for this error is that movel has been implemented to support only data reference expressions. However it should support also array access to data reference expression. This statement has been developed at Sme.UP, so I am assigning this to Franco, in this way we do not lose track of this bug. For any issue please feel free to answer me here or write me an email.

**Comment by ftomassetti** [comment]
I saw that `fun movel(operationExtender: String?, target: AssignableExpression, value: Expression, interpreterCoreHelper: InterpreterCoreHelper): Value {` check the target is a `DataRefExpr`. We could remove that check but then `assignStringToString` it is called and that works only with a `DataRefExpr`

**Comment by f-lombardo** [comment]
Federico, thank you for pointing out the cause of the error:  we will try to fix it.
