### ISSUE TITLE
Fixed size vs variable size strings

### ISSUE THREAD

**Issue by f-lombardo** [smeup/jariko#95]
Concatenating fixed size strings should not truncate trailing spaces.
See test executeARRAY10 in InterpreterTest

**Comment by ftomassetti** [comment]
The program is this:
```
     D ARR1            S              4    DIM(3)
     D MSG             S             12
     **-------------------------------------------------------------------
     C                   EVAL      ARR1(1) = 'AB'
     C                   EVAL      ARR1(2) = 'CD'
     C                   EVAL      ARR1(3) = 'EF'
     C                   EVAL      MSG = ARR1(1) + ARR1(2) + ARR1(3)
     C                   DSPLY                   MSG
     **-------------------------------------------------------------------
     C                   SETON                                          LR
```

My question is:
1) When the program starts ARR1 contains three strings of four characters each. All of the chracters are spaces. Is this correct?
2) When we assign `ARR1(1) = 'AB'` in `ARR1(1)` we get "AB  ", not "AB", correct? The value is not varying
3) When we perform ` ARR1(1) + ARR1(2)` we are summing "AB  " and "CD  ". Both are not varying so the result is "AB  CD  ". Correct?

@benetti-smeup @f-lombardo could you confirm this, please?

**Comment by benetti-smeup** [comment]
Correct for all questions.

**Comment by ftomassetti** [comment]
Perfect, thank you. We are working on a solution.
